"""
This type stub file was generated by pyright.
"""

from tensorflow_hub.keras_layer import KerasLayer
from tensorflow_hub.module_v2 import load, resolve
from tensorflow_hub.version import __version__
from tensorflow_hub.config import _get_extra_deps, _run

"""TensorFlow Hub Library."""
__all__ = ["LatestModuleExporter", "register_module_for_export", "image_embedding_column", "sparse_text_embedding_column", "text_embedding_column", "text_embedding_column_v2", "attach_image_module_info", "get_expected_image_size", "get_num_image_channels", "ImageModuleInfo", "KerasLayer", "Module", "ModuleSpec", "add_signature", "attach_message", "create_module_spec", "create_module_spec_from_saved_model", "load", "load_module_spec", "resolve"]
__all__ += _get_extra_deps()
__all__ += []
