"""
This type stub file was generated by pyright.
"""

"""Utilities for file operations."""
def extract_file(tgz, tarinfo, dst_path, buffer_size=..., log_function=...): # -> None:
  """Extracts 'tarinfo' from 'tgz' and writes to 'dst_path'."""
  ...

def extract_tarfile_to_destination(fileobj, dst_path, log_function=...): # -> None:
  """Extract a tarfile. Optional: log the progress."""
  ...

def merge_relative_path(dst_path, rel_path):
  """Merge a relative tar file to a destination (which can be "gs://...")."""
  ...

