"""
This type stub file was generated by pyright.
"""

from tensorflow_hub import resolver

"""Functions to resolve TF-Hub Modules stored in uncompressed folders on GCS."""
_UNCOMPRESSED_FORMAT_QUERY = ...
class HttpUncompressedFileResolver(resolver.HttpResolverBase):
  """Resolves HTTP handles by requesting and reading their GCS location."""
  def __init__(self) -> None:
    ...
  
  def __call__(self, handle): # -> None:
    """Request the gs:// path for the handle and pass it to PathResolver."""
    ...
  
  def is_supported(self, handle): # -> bool:
    ...
  


